CREATE TABLE table2(f1 int, f2 int);
INSERT INTO table1 VALUES(1,2);
INSERT INTO table1 VALUES(2,4);
INSERT INTO table1 VALUES(3,8);
INSERT INTO table1 VALUES(4,16);
SELECT * FROM table1 ORDER BY f1;

DELETE FROM table1 WHERE f1=3;

CREATE INDEX index1 ON table1(f1);
